spring.main.banner-mode=off
logging.config=./config/logback.xml
#
#app.id=com.alanpoi.lcs
##ConfigService地址, apollo client将从这里得到配置数据, 必须
#apollo.meta=http://172.16.147.14:8080
##配置文件缓存位置  默认位置: /opt/data/{app.id}/config-cache, 必须
#apollo.cacheDir=data
##允许在spring ApplicationContext之前加载配置
#apollo.bootstrap.enabled=true
#apollo.bootstrap.namespaces=application,redis,dubbo,rabbit
#后端推送信令端口
server.push.port=18088
#长连接端口
server.secp.port=1181
#web socket通信端口
server.ws.port=1182

server.port=8081
spring.application.name=im-lc-server

spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=0
spring.redis.timeout=2000
spring.redis.maxActive=100
spring.redis.maxWait=5000
spring.redis.maxIdle=20
spring.redis.minIdle=2
# 连接池配置
spring.redis.jedis.pool.max-active=100
spring.redis.jedis.pool.max-idle=20

dubbo.registry.address=zookeeper://43.199.160.152:2181
# 对应你之前升级的 Dubbo 2.7.x 配置
dubbo.application.qos.enable=false
dubbo.consumer.retries=0
dubbo.consumer.timeout=5000
dubbo.consumer.actives=2
dubbo.consumer.check=false

dubbo.provider.accepts=128
dubbo.provider.threads=32
dubbo.provider.queues=256
dubbo.provider.dispatcher=lcs
dubbo.provider.executes=8
dubbo.provider.threadpool=fixed
dubbo.protocol.port=-1
dubbo.service.protocol=dubbo

qzdim.rabbitmq.host=43.199.160.152
qzdim.rabbitmq.port=5672
qzdim.rabbitmq.username=admin
qzdim.rabbitmq.password=123456
qzdim.rabbitmq.virtual-host=/
qzdim.rabbitmq.lcs.queue.direct.internal=lcs.queue.direct.internal
# 生产者确认机制
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.listener.simple.acknowledge-mode=manual

server.secp.key=./config/dev-pri.pkcs8






